# 1. 모든 지점 프론트엔드 연결
server {
    listen 80;
    server_name *.lucidenglish.co.kr; # 모든 2차 도메인 허용

    location / {
        proxy_pass http://lucid_agent_fe:5173;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # [중요] 접속한 도메인을 그대로 백엔드/비트에 전달
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}

# 2. 통합 API 허브
server {
    listen 80;
    server_name api.lucidenglish.co.kr;

    location / {
        proxy_pass http://lucid_agent_be:8000; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}